version: '3.8'

services:
  mysql_db:
    image: mysql:8.2 # or mysql:8.2
    container_name: dev_database
    ports:
      - "3306:3306"
    volumes:
      - dev_mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DATABASE_PASSWORD
  
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    container_name: dev_nginx
    volumes:
      - ./public:/app/public:ro
    ports:
      - "80:80"

  phpfpm:
    build:
      context: ./
      dockerfile: ./docker/phpfpm/Dockerfile
    container_name: dev_phpfm
    env_file:
      - .env
    environment:
      - DATABASE_PASSWORD
    volumes:
      - .:/app:rw,cached
      - ./var:/app/var

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  dev_mysql_data:
  var:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
