parameters:
    env(DATABASE_PORT):"3306"
    env(DATABASE_NAME):test_db_name
    env(DATABASE_USER):root
    env(DATABASE_PASSWORD):test
    env(DATABASE_HOST):test_db_host
    DATABASE_DRIVER=pdo_mysql